name: Publish gem
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release gem
        run: |
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
            ---
            :github: Bearer ${{ secrets.GITHUB_TOKEN }}
            :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF
          chmod 0600 ~/.gem/credentials
          nix develop -c rake release
